<?php
$order = $this->getOrder();
$payment = $order->getPayment();
?>

<style>
    .button-belluno {
        transition-duration: 0.4s;
        background-color: white;
        color: gray;
        border: 1px solid gray;
        padding: 8px 20px;
        border-radius: 8px;
        font-size: 16px;
    }

    .button-belluno:hover {
        background-color: gray;
        color: white;
    }

    .label-belluno {
        height: 30px;
        font-size: 16px;
        text-align: center;
    }

    .border-belluno {
        border: 1px gray solid;
    }

    .row {
        display: inline-block;
        align-items: center;
    }
</style>

<?php if ($payment->getMethod() == 'belluno_bankslippayment') :
    $digitableLine = $this->getDigitableLineBankSlip();
    $url = $this->getUrlBankSlip();
?>
    <div class="actions-toolbar flex">
        <div class="linhes">
            <h4>Linha digitável</h4>
            <div class="flex">
                <fieldset class="border-belluno">
                    <p class="label-belluno" id="text-digitableline"><?= $digitableLine ?></p>
                </fieldset>
            </div>
        </div>
    </div>
    <br>
    <div class="btn-bankslip-download">
        <input class="action primary button-belluno row" type="button" id="belluno_btn" onclick="window.open('<?= $url ?>');" value=" Imprimir boleto " />
        <button class="button-belluno row" id="button-copy" onclick="copyTextSucess()">Copiar</button>
    </div>
    <br>
<?php endif; ?>