<?php
$order = $this->getOrder();
$payment = $order->getPayment();
$method = $payment->getMethod();
?>

<?php if ($method == 'belluno_bankslippayment') :
    $digitableLine = $this->getDigitableLineBankSlip();
    $url = $this->getUrlBankSlip();
?>

    <style>
        .border-bankslip {
            border: 1px solid gray;
            padding: 10px;
        }
    </style>

    <br>
    <div class="border-bankslip">
        <div class="digitable-line">
            <h3><?= "Informações do boleto" ?></h3>
            <h4>Linha digitável:</h4>
            <textarea readonly rows="1" name="pixer" id="select-this"><?= $digitableLine ?></textarea>
        </div>
        <br>
        <div class="btn-bankslip-download">
            <input class="action primary btn-belluno-boleto" type="button" id="belluno_btn" onclick="window.open('<?= $url ?>');" value=" Baixe o seu boleto aqui " />
        </div>
    </div>

<?php endif; ?>

<?php if ($method == 'belluno_creditcardpayment') :
    $viewData = $this->getViewData();
?>

    <style>
        .border-creditcard {
            border: 1px solid gray;
            padding: 10px;
        }
    </style>

    <br>
    <div class="border-creditcard">
        <h3><?= "Informações do pagamento:" ?></h3>

        <?php
        $num = 0;
        foreach ($viewData as $value) :
            $num++;
            $rest = $num % 2;
            if ($rest == 0) : ?>
                <h4><?= $value ?></h4>
            <?php else : ?>
                <h6><?= $value ?></h6>
            <?php endif; ?>
        <?php endforeach; ?>

    </div>

<?php endif; ?>