<fieldset class="form-bankslip" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none">
    <style>
        .form-creditcard {
            border: 1px solid gray;
        }

        .div-inputs {
            border: 8px solid transparent;
        }
    </style>

    <?php
    $captureTax = $this->getFieldCaptureTax();
    ?>

    <?php if ($captureTax == true) : ?>
        <div class="div-inputs">
            <legend class="legend-bankslip">Cpf/Cnpj do cliente</legend>
            <input type="text" id="client_document" onkeyup="maskDocument(this)" maxlength="18" class="validate-document" name="payment[client_document]"/>
        </div>
    <?php endif; ?>
</fieldset>